config/routes.rb
Rails.application.routes.draw do
  root "homes#top"
  get 'home/about'=> "homes#about"
  devise_for :users
  resources :books, only:[:index,:show,:edit,:create,:update,:destroy,:create]
  resources :users, only:[:index,:show,:edit,:update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  validates :name, uniqueness: true, length:{in: 2..20}
  validates :introduction, length:{maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except:[:top,:about]
  before_action :configure_permitted, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted
    devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<h1>Welcome to <i class="fas fa-book"></i><strong>Bookers!</strong></h1>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
  <h1>
    Welcome to 
    <i class="fas fa-book"></i>
    <strong>Bookers!!</strong>
  </h1>
  <p>
    In <i class="fas fa-book"></i><strong>Bookers,</strong><br>
    you can share and exchange your opinions, inpressions,and emotions<br>
    about various books!
  </p>
<div class="btn-wrapper col-10 mx-auto">
    <div class="row">
  <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3" %>
  </div>
  <div class="row">
  <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-success btn-sm btn-block" %>
  </div>
  </div>
  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/f9617bf6c0.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <%= link_to "Bookers", root_path, class:"navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
            <li class="nav-item active">
              <%= link_to user_path(current_user), class:"nav-link text-light"  do %>
                <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path do %>
                <i class="fas fa-users"></i> Users
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to books_path do %>
                <i class="fas fa-book-open"></i> Books
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i> logout
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to root_path do %>
                <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to home_about_path do %>
                <i class="fas fa-link"></i> About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path do %>
                <i class="fas fa-user-plus"></i> sign up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path do %>
                <i class="fas fa-sign-in-alt"></i> login
                <% end %>
            </li>
        <% end %>
           </ul>
        </div>
      </div>
    </nav>

    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>

    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>